name: CI tests

on: push

jobs:
  tests:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: yarn test
