name: CI tests

on: push

jobs:
  tests:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn --frozen-lockfile
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
      - run: yarn test
